import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import duaTitle from "@/public/duaTitelimg.png";
import Header from "@/components/Header";
import NavBar from "@/components/NavBar";
import SideNav from "@/components/sidenav/SideNav";
import SettingsBar from "@/components/SettingsBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: { duaTitle },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#E2E2E2] flex`}
      >
        <NavBar />
        <div>
          <Header />
          <main className="flex">
            <SideNav />
            {children}
            <SettingsBar />
          </main>
        </div>
      </body>
    </html>
  );
}
